language: minimal
os: linux
dist: xenial
group: edge
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # for updates check developer.android.com/studio#downloads (current 26.1.1)
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip

addons:
  apt_packages:
    - pandoc

before_install:
  # set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  # set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
install:
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager --licenses >/dev/null
  - yes | sdkmanager "platforms;android-27"
before_script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ls -la
  - java -version
  - sudo apt-get install openjdk-8-jdk
  - java -version
  # set executable flag for gradle wrapper
  - chmod +x gradlew

script:
  - ./gradlew opensrp-app:clean opensrp-app:jacocoTestReport --stacktrace

after_success:
  - ./gradlew opensrp-app:coveralls --stacktrace


after_failure:
  - pandoc opensrp-app/build/reports/tests/index.html -t plain

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=

before_deploy:
  - echo "sonatypeUsername=$SONATYPE_USER" > ~/.gradle/gradle.properties
  - echo "sonatypePassword=$SONATYPE_PASS" >> ~/.gradle/gradle.properties

deploy:
  provider: script
  script: ./gradlew :opensrp-app:uploadArchives -PmavenLocal=false
  on:
    tags: true
