language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: precise

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2
    # git hub token
    - secure: U1vPvVecZW09b+IVf/AY9x48BEe3S9no/5fmmVvJbNMWVI0KbWcx0gzZAfDy1wv2YAFV4LMcXEQyu54F4A62iSoUHw0Qd68fCH/HBNVIHZIOWxW6QB5U3ixJrbBSirS+T6zpHgK8YfaRb+WeHn1+JoTjJC/4hZZ46rXoLUSZJutPInydLCG1EvqcFKYMyNQ3Ai8r1Y/PQB5NcZ3RHdsgfunU8RAXSpsLG22L9p6JlEspJjKkpWbh2g3ZqRrVxqYg0fGG0ujQhZFtmvEVTkPJGdmE4uWrAmX3+O5P2X5FZlLg3JJyO95c5UD5mhk5H1SZSXL1y1IqIxOBpAJm5AQPgNXLnNUa+wEgKfJZeNTNeskw1Zkta4V9wlDXk1Uzone+tZqDr669BnWxitKS0U4bcQB+8URSZq6jrf6aBG535m4pG46xtYRBmYR5A2DkKwJJGwsmYCtJO4lJqLwgPpb4/jIbAAjmRN2jAjpCwn5CcR6TPHGEjWFmgypAd9HdpXMkpfN+X+bgbB8mZVYS4a39QCSyXqppHe0e7UqJWIHHpYuqI+ziTu8/Xw5/A8gCtSAdFzw4dkZHTueFdmZkoRGANdiKkgEiWbH5LQTWovadimiuDmGTI1wVeJIZZ9vUMwbygaTEgncx8F4tURMh9xCElbsK0muwvmC8QVfrRnboGZc=

android:
  components:
    # tools required
    - tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-28

addons:
  apt_packages:
    - pandoc

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  # Enable the line below once we get all the test passing, currently most of the tests are failing 
  # so we'll just if the project compiles
  #Run All tests Unit and Instrumentation
  - travis_wait ./gradlew opensrp-app:clean opensrp-app:jacocoTestReport coveralls --stacktrace
  # Generate javadoc
  - ./gradlew javadoc

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: opensrp-app/build/docs/javadoc/
  on:
    branch: 419-deploy-java-docs